#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <new-version>" >&2
  exit 1
fi

new_version="$1"

if [ "$new_version" != "${new_version#v}" ]; then
  echo "Error: The new version shouldn't be prefixed with a \"v\"." >&2
  exit 1
fi

set -x

sed -i meson.build -e "s/^  version: '.*'/  version: '$new_version'/"

echo -n "Minimum wlroots version? "
read -r wlr_version_min

sed -i meson.build -e "s/'wlroots', version: '.*'/'wlroots', version: '>= $wlr_version_min'/"

git add meson.build
git commit -m "Update version to $new_version"